package ders27_immutableClasses_DateAndTime;

public class C01_cc {
    public static void main(String[] args) {
        // bu kod calistiginda java kac obje olusturur

        String str = "Ali";

        for (int i = 0; i < 10; i++) {
            str += ".";

            System.out.println(str);
            /*  Ali.
                Ali..
                Ali...
                Ali....
                Ali.....
                Ali......
                Ali.......
                Ali........
                Ali.........
                Ali..........
                Ali.......... */

        }
        System.out.println(str); // Ali..........
    }
}
